### ISSUE TITLE
Cannot modify srcmounts using mergerfs.ctl

### ISSUE THREAD

**Issue by DavidFair** [trapexit/mergerfs-tools#141]
Following https://github.com/trapexit/mergerfs/pull/1171 we can't modify source mounts using `mergerfs.ctl` as expected.

From the linked PR it looks like this was to workaround a bug in the "current setup", so I'm unsure if it's planned to make the `srcmounts` rw again in the future or leave it ro for good?

If it's going to stay ro for the long-term or forever, is it worth either raising a dedicated exception rather than `Read-only file system`  (which is confusing)? Or is it worth dropping this functionality from the tooling all-together?

**Comment by trapexit** [comment]
The `srcmounts` argument has long been deprecated in favor of `branches`

I guess I forgot to change that tool because really they are intended as examples to people and not production tools

The whole interface is going to be going away in v3. Another reason I don't much pay attention to these tools.

It returns EROFS because that's the error mergerfs returns for all read only arguments. EINVAL for invalid values. 

I'll replace srcmounts for branches.

**Comment by trapexit** [comment]
OK. Try the latest version.

**Comment by DavidFair** [comment]
That's resolved it, I suspected that it was just changing from `srcmounts` to `branches` but I wanted to check

In this case, it was a handy tool whilst I drained / swapped by disks out of the pool, rather than using `setfattr` each time.

Thanks for resolving this :+1:
