### ISSUE TITLE
create rebalancing tool

### ISSUE THREAD

**Issue by trapexit** [trapexit/mergerfs-tools#3]
A tool which would, given a particular drive in the mergerfs pool, rebalance those files across the remaining pool.

Easiest is probably to automate creation of a new pool in temporary locations which excludes the target drive and then rsync's the data from the target back into the pool.

**Comment by davidjmurray** [comment]
Can you clarify what you mean by rebalance.

Is this a process for removing the selected drive from the pool?
Or is it a process where the drives are all made to balance to an equal percentage (or attempt to honor whatever policy has been selected)?

I am currently running mergerfs and snapraid and I would be interested in contributing to a rebalance tool if you can provide a bit of a guideline.

Cheers,

**Comment by trapexit** [comment]
I mean whatever people want to do that could be considered rebalancing :)

Could mean taking a drive which is "overfilled" and moving files to other drives. Could mean taking files which span multiple drives in a single directory and put them all on a single drive.

**Comment by davidjmurray** [comment]
OK,
I would like to rebalance drives to the same percentage. This is typically what I do manually (approx.) when I add a new drive to the pool.

I will continue with my automated script.

**Comment by ajclark** [comment]
I'm super excited for this tool. I keep checking back to this issue to see if there has been any progress. 👍 for rebalancing drives to an equal percentage.

**Comment by restfuladi** [comment]
davidjmurray, do you mind sharing your script?

**Comment by Wintersdark** [comment]
Oh, absolutely yes.  I'd love to see this - typically I buy a new HDD every time my existing pool fills, but this tends to mean that I've got a bunch of totally full drives then one empty one.  I manually shuffle a couple folders around to get more free space on the old drives, but I'd love an automated too that could rebalance drives.

**Comment by tomewarren** [comment]
Keeping an eye on this as I have a few drives with 2+tb and others that have only a couple gb...

@davidjmurray please share your script to get us by until we get a proper tool...

**Comment by najmead** [comment]
I would love a tool that could any (and preferably all) of the following;

1. When you add a new drive to the pool, redistribute existing data to include the new drive. 

2. When you want to remove a drive from the pool, take all the data from the drive and redistribute to the other drives (assume there is actually space)

3. Re-organise existing content to meet certain hierarchy requirements.  eg, where the content of a directory is is split across several drives, consolidate it into a single drive, or something like that.

**Comment by trapexit** [comment]
The problem with a rebalancing tool is "rebalance" means different things depending on the policy (from the mergerfs pov). Due to the complexity the `mergerfs.balance` tool is single function and can perhaps be made more flexible later.

I'll document more of how it works shortly but basically it looks at all drives in a mergerfs pool and sorts them by percentage filled. It will pick a file (basically at random) from the most filled and move it (using rsync) to the least filled drive. It will then perform that behavior again till the difference in percentage between the most filled and least filled is lessthan or equal to the value provided (defaulting to 10%).

I've made it specific to mergerfs (you give it a mergerfs root path and it'll look up all the drives) but I'll probably make it so it can be passed a list of drives so balancing can be done more generically.

A tool to make draining a drive is coming though it simply wraps mounting a new mergerfs instance in a temp directory that is setup the same as an existing one minus the drive to drain and then rsync's into it.

Once that is finished I'll look into the consolidation tool.

**Comment by aphirst** [comment]
Regarding the consolidation tool, I expect that all aspects of the problem could be "tricky".

* Working out how best to break up the data structure to ensure contiguity of the topmost-possible directories - in many cases, this arrangement will be obvious, e.g. if the top folders are all 3x 3TB and the constituent disks are 3x 4TB, but I can see that becoming a complicated analysis when it comes to smaller, lower-down directories (bin-packing?), or if certain members of the pool have special properties
* Working out in which order to actually perform the moving around  - a naive algorithm could end up being very inefficient, especially if the 'scratch' space on some disks is small, and ultimately it would be useful to incorporate the read/write performance of each member into the decision-making process (and a nightmare if the performance of each member is significantly affected by other members being actively accessed at the same time)

I originally wanted to make a [Feature Request] for this, but since you mentioned this in an existing Issue, figured it best to just dump my thoughts here. I hope it's not an intrusion.
