### ISSUE TITLE
dedup doesn't print filenames

### ISSUE THREAD

**Issue by DominicMe** [trapexit/mergerfs-tools#35]
Running dedup with the following command:

`sudo mergerfs.dedup -d manual /mnt/mergerfs`

Result is: 
`Which to keep? ('s' to skip):`

This repeats every time s is entered. Nothing else is printed. How do I know what to skip? Is it a bug or am I missing something here?

**Comment by DominicMe** [comment]
I am blind, missed --verbose option :)

**Comment by trapexit** [comment]
Yeah. Though ideally it would force verbose on manual. I just haven't added it yet.

**Comment by DominicMe** [comment]
Also there are discrepancies between git and -h documentation. For example mergerfs.dedup -h has "-e, --execute without this it will dryrun" while git page does not. Double -v usage is very handy but undocumented.

Another issue I am seeing is this error with fsck script. It is missing parentheses on line 69. After that is fixed I had to manually install python-xattr (Maybe it's better to just include all the scripts along with the main package? This would be a lot more convenient as dependencies would be installed automatically with the package.)

I am now getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.fsck", line 192, in <module>
    main()
  File "/usr/local/bin/mergerfs.fsck", line 178, in main
    check_consistancy(fulldirpath,verbose,size,fix)
  File "/usr/local/bin/mergerfs.fsck", line 130, in check_consistancy
    paths = getxattr(fullpath,"user.mergerfs.allpaths").split('\0')
TypeError: a bytes-like object is required, not 'str'

```

I am on Arch Linux so python 3 is default btw.

**Comment by trapexit** [comment]
The problem is you're using Python 3 which this script is not made for. I've not yet converted them. xattr is for Python 2.

And yes... the docs are out of date. There has been limited interest in the tools so I've not focused on keeping them up to date when I change the tools. If there are specific issues then file specific tickets and I'll get to them when I have time.

**Comment by DominicMe** [comment]
Makes sense. xattr is available for both version of python btw. Fix is simple so I created a pull request.

I think there would be a lot more interest in these tools if they were easier to find / discover. Packaging them along with mergerfs package would help a lot in this regard.

**Comment by trapexit** [comment]
They are referred to a number of times in the mergerfs documentation and pinned to my github page just below mergerfs. I don't want to package them together because they use different programming languages and I don't want to have to release a new version of mergerfs in order to release the tools.

I included them long ago and packagers complained and it was a pain to update all the time.
